# staticcheck configuration for ZoneLint
# https://staticcheck.io/docs/configuration/

[rule._]
  [rule._.options]
    exclusions = [
      { rule = "ST1000" },
      { rule = "ST1003" },
      { rule = "QF1001" },
      { rule = "QF1003" },
      { rule = "QF1015" },
      { rule = "SA4000" },
      { rule = "SA5011" },
      { rule = "U1000" },
    ]
