# staticcheck configuration for ZoneLint
# https://staticcheck.io/docs/configuration/

all: true
ST1000: false
ST1003: false
QF1001: false
QF1003: false
QF1015: false
SA4000: false
SA5011: false
U1000: false
